Foundation-19/Hail-Mary

code/game/objects/structures/ghost_role_spawners.dm
Adds an entirely self-contained FEV pit.
It starts with 3 uses of mutants, and for every human you put in there you get another use.
You only need to place one of these to enable the mutant faction.
There's one small issue with mutants, being that they don't actually spawn with legs?
Out of scope for this PR
:cl:
add: Added FEV pit.
/:cl:
=> Adds FEV Pit.

code/modules/jobs/job_types/enclave.dm
yippie
loadouts standardised entirely, only role that has a choice in gear is specialist because. y'know. that's their whole gimmick.
all roles below sergeant get an assault carbine, the sergeant gets a LSW, the lieutenant and captain get FALs and a sidearm.
specialists can choose between being a combat medic or an engineer (meds or a grenade launcher)
also gives all roles a minor boost via survival kits since for some reason they... don't have them? whereas most roles do.
:cl:
add: Standardised loadouts for the Enclave.
/:cl:
=> enclave standardisation

code/modules/jobs/job_types/bos.dm
as according to the design doc, bos loadouts are basically just all gone now, knights have AER9s and all other roles start with aer12s with the obvious exceptions of scribes, initiates, the proctor and the elder.
the only roles currently with loadout choices are:
scribes (to choose junior/normal pins)
initiates (choosing knight-aspirant / scribe-aspirant)
proctor
elder
subject to change
:cl:
add: Standard BOS loadouts.
/:cl:
=> standardising bos loadouts

.vscode/settings.json, _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm, code/game/objects/effects/landmarks.dm, code/game/objects/items/storage/boxes.dm, code/modules/jobs/job_types/bos.dm, code/modules/jobs/job_whitelist.dm, code/modules/jobs/jobs.dm
currently awaiting host approval
reworks BoS slots, power and loadouts to relegate them to being a minor faction with the potential to become a more credible threat the longer the round goes on.
HP: 1
Paladin: 1
SK: 2
Knight: 3
SS: 1
Scribe: 2
Initiate: 4
Only the HP and Paladin spawn with 'good' gear - only the HP had an actual choice in loadouts. The Paladin gets an AER12, the remaining roles get AER9s or AEP7s, or similar sidegrades. RnD has been removed from the Brotherhood.
The current main strength of the BoS lies in their scribes and knights - each role spawns with two random weapon blueprints. Knights spawn with ballistic blueprints, Scribes spawn with energy blueprints. The Senior roles receive better blueprints, with the SS having the rarest due to only being one slot. These …
=> bos rework

code/datums/traits/good.dm, code/datums/traits/negative.dm, code/datums/traits/neutral.dm, code/game/objects/items/melee/f13onehanded.dm
Ensures unarmed combat is no longer an instant win. This includes balancing unarmed weaponry and nerfing/removing existing unarmed quirks. 
Removes a bunch of vestigial CB code that have no reason to be in the game.
:cl:
del: Removed a shit ton of traits that existed purely for weird furry purposes.
del: Removed VERY easily exploitable traits that will most definitely be abused by the playerbase if it launches.
balance: Rebalanced iron fist, removed a majority of OP unarmed traits from the start menu.
/:cl:
=> Total unarmed balancing + quirk changes

code/modules/jobs/job_types/eastwood.dm, code/modules/jobs/job_types/legion.dm, code/modules/jobs/job_types/ncr.dm, code/modules/projectiles/guns/ballistic/automatic.dm, code/modules/projectiles/guns/ballistic/rifle.dm, code/modules/projectiles/guns/ballistic/shotgun.dm
Nerfs the Legion a little, though I think I already did before.
The only roles with a roundstart gun option is the Centurion, the Decanii, the Vexillari, Explorers and the Veteran Legionnaire.
Centurion:
Paladin Hunter - M1919 removed, replaced with the BAR. CQC removed.
Ranger Hunter - AMR removed, replaced with a unique DKS/Sniper Rifle.
Warlord - Given a unique lever-action shotgun.
Veteran Decanus:
Stupid shotgun loadout got replaced w/ a lever-action shotgun instead of a trench.
Prime Decanus left untouched.
Recruit Decanus:
Backlinder Loadout: M1 Garand replaced with a unique trail carbine.
Explorer:
SKS replaced with a trail carbine.
Auxilia:
Given an Auxiliary Militia role. Starts with recruit armour, tribal paint and a plain spear.
Rest of the Legion loadouts are fine / are all …
=> legion fixes and more

code/datums/components/crafting/recipes/recipes_medicine.dm, code/game/objects/items/storage/f13storage.dm, code/modules/reagents/chemistry/recipes/medicine.dm, code/modules/reagents/reagent_containers/hypospray.dm, code/modules/reagents/reagent_containers/patch.dm, fallout/reagents/medicines.dm
Introduces two new clotting agents - a chemical hemostatic and Hydra.
Hemostatic is made with 1 parts Morphine and Bicaridine to two parts styptic powder.
Hydra is made with three cave fungus and three broc flowers.
You can make them in the medical crafting menu. Hemostatic has to be chemically synthesised first, and then made w/ syringes to make injectors.
Both of these are powerful coagulants that stem the flow of bleeding. However, it does not *close the wounds themselves*, and they are meant to be used in conjunction with sutures or bandages. Here is an example of how to use them:
- You are hit with a bullet in the chest.
- You receive a puncture wound.
- You are losing 4u of blood per tick.
- You apply a hemostatic applicator/a hydra patch.
- This reduces the rate at which you lose …
=> medical update - Wounds Made Easy (I want to fucking die.)

code/modules/jobs/job_types/eastwood.dm
Currently the detective spawns in with a 'revolver template' in .357. This replaces it with a common .357 revolver. Yippie.
=> Fixes Detective Loadout

code/modules/cargo/packs/security.dm, fallout/code/modules/reagents/chemistry/recipes/fermi.dm
As the title says, removes the slime crossbreed crates and the chance for the slime grenade to spawn in cargo to stop people from doing OP shit like making slime speed potions, consciousness transference potions, etc.
:cl:
del: Removed slimes from cargo
/:cl:
=> Removes slime extracts from cargo

code/datums/components/crafting/recipes/recipes_misc.dm, code/game/machinery/doors/poddoor.dm, code/modules/vending/wardrobes.dm
Shutters don't drop -5 plasteel anymore and should instead drop the proper amount of prewar material.
:cl:
fix: fixes shutters dropping negative amount of plasteel when deconstructed
/:cl:
=> Shutters drop proper amount of prewar materials now when deconstructed

code/modules/jobs/job_types/bos.dm
Senior scribes had a bug causing the advanced blueprint that they own to not spawn properly due to a lack of inventory space. This has been fixed via moving the advanced toolbelt they spawn with in their bag over to their belt slot. This has also been done to the scribe for consistency.
Scribes and senior scribes have also been given the full chemwhiz list, allowing for stimpack production via stimfluid while keeping the chem recipes that they had before.
:cl: thatsmamaluigitoyoumario
tweak: Scribes+Senior Scribes have been given full chemwiz crafting recipe list
fix: Fixed the advanced senior scribe blueprint not spawning on the senior scribe
/:cl:
=> Senior Scribe and Scribe Bug Fix+Changes

code/game/machinery/doors/door.dm, fallout/obj/structures/simple_door.dm
Reverts an admin QoL alert to how it was on Big Iron. I'm unsure why it was commented out in the first place, but I uncommented it. Now we'll know more easily if bases are being raided.
:cl:
admin: uncommented door destruction alerts
/:cl:
=> Alerts admins upon door destruction

code/modules/reagents/chemistry/recipes/medicine.dm, fallout/reagents/medicines.dm
This PR aims to unfuck the stimfluid recipe and the hemostatic recipe by changing the bicard, morphine to brocjuice and xanderjuice. Prior to this PR hemostatic used three of the five reagents in stimfluid causing people to make hemostatic instead of the much preferred stimfluid.
Stimfluid, Im unsure why 25 units made 5 units of stimfluid, but even poke said stimpacks where near impossible to make, since who would want to make all those things just to get 5 units of shit for their work? Well I am aiming to change that 5 units to 25u, to make stimpacks available to be made again with out the person wanting to kill them self through the process
EDIT: Fixed super stim packs not healing by yoinking the Stimpak healing and adding a .7 to brute and burn, 
From testing stimpacks heal around 7 …
=> Unfuck-stim-Hemo

code/modules/reagents/chemistry/reagents/other_reagents.dm, code/modules/reagents/chemistry/recipes/slime_extracts.dm, code/modules/reagents/reagent_containers/syringes.dm
Comments out two reagents I missed when doing my first mutation toxin removal.
:cl:
del: removed advanced mutation toxin and gluttony's blessing
/:cl:
=> Removes more ways for slimes and morphs to be spawned

code/modules/mob/living/carbon/human/examine.dm
Hopefully it will once again show how long a player has been disconnected for when examining them, which should make it easier for players to tell if someone likely isn't coming back and can be matrixed or not.
:cl:
fix: fixed the message for disconnected clients not showing the time they've been DC'd for when examining them
/:cl:
=> Fixes disconnected player timers not showing

code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm, code/modules/mob/living/simple_animal/hostile/f13/centaur.dm, code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm, code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm, code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm, code/modules/mob/living/simple_animal/hostile/f13/insects.dm, code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm, code/modules/mob/living/simple_animal/hostile/f13/raider.dm, code/modules/mob/living/simple_animal/hostile/f13/rattler.dm, code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm, code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
Previously if you were attacked by a deathclaw or any other mob they would only attack you until you went to critical condition. Now most mobs that are on the stronger side will fully kill you, making mobs way more threatening to fight.
A full list of every mob that will fully kill you:
- Sentrybots
- Securitrons
- FEV Created Centaurs (The strong ones)
- Abominations
- All deathclaw types
- Enclave AI NPCs
- Brotherhood Paladin NPCs
- Legendary Ghouls
- Ant Queens
- Mirelurk Hunters
- Legendary Raiders, Raider Bosses, and Junker Bosses
- Rattlers (An unused mob, but they were strong enough that I gave it to them just incase)
- Super Mutants
- Gutsys, Robobrains, Protectrons, and Assaultrons
:cl:
balance: rebalanced when most mobs will stop attacking you
/:cl:
=> Lets stronger mobs kill people

code/__DEFINES/say.dm, code/modules/mob/dead/new_player/new_player.dm
This adds back the Minimum 75 characters required for in flavor text.
Shorter than previous servers, where the minimum was 100.
Might also help people to invest themself a bit more in IC maters.
=> Readds back flavortext minimum Requirement.

code/modules/jobs/job_types/legion.dm
Someone set the stack spawn numbers to zero for every currency that isn't caps, so giving Treasurer caps is easier than fixing that problem in f13Cash.dm
- [no ] You tested this on a local server.
- [idk ] This code did not runtime during testing.
- [yeah ] You documented all of your changes.
:cl:
tweak: Replaced the Aureus that Treasurer spawns with with 500 caps flat (not a chance based amount)
/:cl:
=> Update legion.dm - give Treasurer caps (500)

code/datums/traits/good.dm, code/modules/clothing/suits/bigiron_suits_factions.dm, code/modules/mob/living/carbon/human/human_movement.dm
Fixes the NCR's flak vest to be the correct LIGHT armor type.
Fixes the 'speed bug' for Super Mutants, at least it *should*.
Disables the Speed Walker perk until it can be changed to work with AGI scaling.
=> Small Fixes - Flak Vests, Mutant Speed Bug, Speed Walker

config/maps.txt
WARNING THIS IS HALF TESTED, but should work. 
Removes balitmore from rotation, meaning it wont ever be selected again until it is reworked.
:cl:
adjusted: maps.txt config. 🤡 
/:cl:
=> Adjust: Remove Balitmore from Rotation

code/game/objects/items/melee/f13twohanded.dm
Big thanks to Chappy for abusing the proton axe's EMP function in his powergamer kit so we could remove it from the game.
Takes out the EMP spam from the proton axe. Not only incredibly broken but also spams the ghostchat with EMP explosion notifications. 
:cl:
del: Removes proton axe EMP
/:cl:
=> Removes EMP Function on Proton Axe
