code/__DEFINES/jobs.dm, code/modules/jobs/job_types/bos.dm, code/modules/jobs/jobs.dm
Adds in BOS jobs, as requested; 
Elder, Paladin Commander, Star Paladin, Paladin, Proctor and Knight-Captain at 1 slot
Scribe, Knight-Sergeant and Sr Scribe at 2 slots
Knight at 4 slots.
:cl:
add: Added BOS back, as requested.
/:cl:
=> Adds in BOS jobs

code/game/objects/items/melee/_melee.dm, code/modules/jobs/job_types/_job.dm, code/modules/mob/living/carbon/carbon.dm, hailmary.dme
Adds the first SPECIAL - Strength.
Strength increases your melee damage by 2 points for every point above 5, and reduces it by 2 for every point below 5.
:cl:
add: Added STRENGTH
/:cl:
=> S.P.E.C.I.A.L - S(trength)

code/_onclick/item_attack.dm, code/datums/components/crafting/crafting.dm, code/datums/components/crafting/recipes.dm, code/datums/components/crafting/recipes/recipes_misc.dm, code/modules/client/preferences.dm, code/modules/mob/living/carbon/carbon_sprint.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/mob/living/carbon/human/species.dm, code/modules/mob/living/damage_procs.dm, code/modules/mob/living/life.dm, code/modules/mob/special_stats.dm, code/modules/projectiles/ammunition/_firing.dm, code/modules/projectiles/gun.dm, hailmary.dme
Adds certain buffs depending on S.P.E.C.I.A.L. stats:
Strength: affects melee damage, +/- 2 dmg per lvl above/below 5 (full desc will be omitted after that)
Perception: -/+ 5 deg of bullet spread (reduction at higher levels, addition at low)
Endurance: +/- 5 maxHealth per lvl, burn + poison damage multiplier
Charisma: mood buffs and debuffs for looking at you
Intelligence: Guns can be INT (or any stat, really, general proc can be overridden for specific guns) locked, crafting recipes can have min INT requirement, crafting is unavailable at <=3 INT
Agility: Movespeed modifier of -/+ 0.05 and +/- 10% sprint stamina usage per lvl
Luck: Currently nothing
:cl:
add: Added S.P.E.C.I.A.L. system implementation.
/:cl:
=> S.P.E.C.I.A.L. implementation

code/modules/jobs/job_types/bos.dm
fixes some equipment spawning bugs the bos previously had due to some oversights on my part
:cl:
fix: bos actually spawns with guns
/:cl:
=> bos standardisation bugfixes

code/modules/jobs/job_types/bos.dm, code/modules/jobs/job_types/enclave.dm
bos get t-45 and t51, enclave apa
i fucking hate my life
:cl:
add: old pa
/:cl:
=> old pa back

config/config.txt
Changes the hostedby to Preston Garvey because it's funny.
Changes the hosted by section to say 'Preston Garvey' because it's funny.
=> hostedby 'fix'

config/config.txt
Now the Mexicans (players) can pour in.
Turns off the system CB used to block out new connections entirely.
=> Disables Border Control

code/__DEFINES/atom_hud.dm, code/modules/mob/dead/new_player/new_player.dm, code/modules/mob/living/living.dm, code/modules/mob/logout.dm
Fixes 2 (2200) runtimes, null names, min flavor text and ooc_notes req
=> Shit removal

code/game/objects/effects/landmarks.dm
whopp
:cl:
add: enclave captain spawn kill me
/:cl:
=> captain spawn

code/modules/pool/pool_main.dm
you dissapoint me
:cl:
fix: fixed water
/:cl:
=> fixed water

code/game/objects/items/stacks/medical.dm
bloodleaf salve won't be put on as "a the bloodleaf salve" or anything like that
:cl:
fix: the the bug
/:cl:
=> the the fix

code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
=> Runtime fix

fallout/code/modules/client/loadout/__donator.dm
=> no donor loadouts

code/__DEFINES/armor.dm, code/game/objects/items/modkit.dm, code/modules/clothing/head/f13factionhead.dm, code/modules/clothing/suits/arfsuits.dm, code/modules/clothing/suits/arfsuits_unused.dm, code/modules/clothing/suits/f13factionarmor.dm, code/modules/jobs/job_types/ncr.dm
Does the Legion and NCR armors.
:cl:
/:cl:
=> Legion and NCR armor

_maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Need to do more later.
Edits the map some, particularly the BOS base. Will do more after the tests.
=> Rudimentary Map Fixes - Starter Edition

code/__DEFINES/combat.dm
title
:cl:
balance: crit back to normal
/:cl:
=> returning crit to normal values

code/modules/projectiles/guns/ballistic/automatic.dm
title
:cl:
fix: gauss rifle has a sprite now
/:cl:
=> fixes gauss rifle sprites

code/game/objects/items/fish.dm, code/game/objects/items/fishingrod.dm
What this PR does is removes eel from fishing and adds in the shark. Shark eggs can be grinded up to be used like regular eggs only giving yolks. However can be used instead of left out like many of the rest of them. Regardless I present to you the landshark.
:cl:
add: Shark
/:cl:
=> Fish Addition: Shark replaces Eel

code/game/objects/items/loadout_beacons.dm
no seriously. sleeping carp? tf?
:cl:
bal: no sleeping fucking carp hello??
/:cl:
=> getting rid of some of the ridiculous waster kits

code/modules/jobs/job_types/bos.dm
:cl:
tweak: sentinel loadout
/:cl:
=> Makes sentinel more than just reskinned elder

code/__DEFINES/traits.dm, code/__DEFINES/wounds.dm, code/datums/traits/good.dm, code/game/objects/items/stacks/medical.dm, code/modules/surgery/organs/tongue.dm
Comments out all code pertaining to lick healing, left licking in for those roleplaying oddballs since it would be too much to nuke it entirely.
=> Removes Lick Healing & Special Tongues (not abductors just in case)

code/modules/projectiles/projectile/bullets/rifle.dm
Makes it not able to blast walls and doors around, only mobs & players.
=> Ultradense - Mobs Only

code/game/objects/structures/tables_racks.dm, code/modules/jobs/job_types/legion.dm
What this PR does is fixes the legion surgery table as it had multiple now it fixes again. Bandana legion fixes too.
:cl:
fix: Butchers table and Bandana fix
/:cl:
=> Bug Fix: Butchers table and Bandana Legion Fix

_maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm, _maps/map_files/Pahrump-AB/Pahrump-AB.dmm, code/game/machinery/dance_machine.dm, code/modules/hydroponics/grown/random.dm, code/modules/hydroponics/grown/tobacco.dm, code/modules/hydroponics/plant_genes.dm, code/modules/jobs/job_types/bos.dm, code/modules/jobs/job_types/oasis.dm, code/modules/jobs/job_types/wasteland.dm, code/modules/projectiles/guns/ballistic/revolver.dm, code/modules/reagents/chemistry/recipes/pyrotechnics.dm, code/modules/research/techweb/all_nodes.dm, code/modules/research/techweb/nodes/medical_nodes.dm, code/modules/research/techweb/nodes/misc_nodes.dm
i fucking mispathed the sprite kms
also fixing some spawn issues regarding support roles and fixes the mayor loadout
fixes some preacher issues
reworks bos minorly
only one paladin, HP removed
knight slots increased by two, initiate by one.
circuits removed.
chembomb shittery disabled.
=> last minute fixes

code/modules/mob/dead/new_player/new_player.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/mob.dm, code/modules/mob/mob_defines.dm
https://github.com/Foundation-19/Big-Iron/pull/17
https://github.com/AtomBombf13/AtomBomb/pull/245
=> Port of a Port for Matrix Logging

code/modules/admin/admin.dm, code/modules/client/verbs/looc.dm
Another Admin option we needed just in case.
=> LOOC Banning

code/modules/reagents/reagent_containers/hypospray.dm, code/modules/reagents/reagent_containers/patch.dm
Gives stimpaks some delay, returns super stims to being super stims and not god mixes @ 62 mixed reagents.
=> Stim Delay + Super Stim Nerf

_maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm, _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm, _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
A holy fuckload of fixes, updates and general QoL.
Updates the map to be not-shit, will need more work.
BOS base is unfinished, and the Khans' base needs addressing.
Same goes for the Followers situation, needs addressing but blocked-off their bottom floor for now.
Let's hit it.
=> Major Map Update

_maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm, code/datums/components/crafting/recipes/recipes_tailoring.dm, code/modules/client/verbs/ooc.dm, code/modules/clothing/custom/custom_clothing.dm, code/modules/clothing/head/f13factionhead.dm, code/modules/clothing/head/f13head.dm, code/modules/clothing/suits/arfsuits_unused.dm, code/modules/jobs/loadout_ingame.dm, code/modules/mob/dead/new_player/sprite_accessories/undershirt.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/species_types/supermutant.dm, code/modules/projectiles/guns/ballistic/automatic.dm, code/modules/projectiles/guns/misc/medbeam.dm, modular_BD2/legio_invicta/code/legio_invicta.dm, tgui/packages/tgui/interfaces/LoadoutSelect.js
-adds a check for shrinking dummmies
-harddel will tell the name of the deleted mob
-ooc now uses ooc name
-armor platable armors part 1
=> More small changes

_maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm, _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm, _maps/map_files/Pahrump-AB/Pahrump-AB.dmm, code/modules/clothing/suits/arfsuits.dm, code/modules/jobs/job_types/eastwood.dm
Gives them botany (no RnD getfucked) and makes it more clear that they're a town clinic. 
Also adding loadouts to mayor to allow them to show which area of the town they ICly lean towards the most (Sherrif/Clinic/Merchant/Standard), 
the loadouts don't make them have less/more power it's purely cosmetic. And a bit for gimmicks (do you want it to be a medical focused mayor or a mayor who is focused on the law)
=> nothingbutpain (Town Clinic Changes)

code/modules/projectiles/guns/energy.dm, code/modules/projectiles/guns/energy/plasmaf13.dm
I had already fixed this same bug with this code on CB so it should work here
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Fixes the rotation when holding certain weapons

_maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Reverts Foundation-19/Hail-Mary#157
BAD
=> Revert "bird"

code/modules/client/preferences.dm
Karl complained
:cl:
admin: admins can now change their ghost form even if not byond members
/:cl:
=> Lets staff have funny ghosts

_maps/map_files/Baltimore/baltimore_surface.dmm, _maps/map_files/Baltimore/baltimore_underground.dmm, _maps/map_files/Baltimore/baltimore_upperlevel.dmm
Reduces the ammount of Nest, and mob spawn arround the Baltimore map.
Also removes that one hole that leads to a radspider dent.
=> Removes holes in map + Reduce spawns

code/game/mecha/combat/phazon.dm
=> Less fast NCR Truck, Less tanky too, and less fuel consumated by the Legion balloon

_maps/map_files/Baltimore/baltimore_surface.dmm, _maps/map_files/Baltimore/baltimore_upperlevel.dmm
Just rempaces them with ghouls. Classic. Only on baltimore, those on Mexico are under the Mexico PR.
=> Removes zombie on Baltimore

code/controllers/subsystem/nightcycle.dm
fixes runway missions runtiming on load
=> fix away mission for realsies

_maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
Not sure if this is a bug during the round or what but I checked, took 0 damage from melee/ranged so this'll fix them.
Not much else to say.
=> Fixes the ghoul-bunker (found out they're invincible)

code/game/objects/items/melee/f13powerfist.dm, code/modules/jobs/job_types/bos.dm, code/modules/jobs/job_types/legion.dm, code/modules/jobs/job_types/ncr.dm
Changes made to one of the loadouts for legion/BoS/NCR. 
NCR got what I'd call a very minor buff (1 extra BP), 
BoS got a nerf (no more lewis gun PC but now they have a melee/plas-pistol loadout)
Legion cent got what I'd say is a buff but in all fairness is more of a neutral change. (Cent gets a melee loadout, BAR removed.)
=> mild changes here and there. (small balance changes)

code/__DEFINES/vote.dm
What this PR does is reverts back the ("Ginormo Megaballs","Couch-Sized Butts","Send Pizza","Bedlike Gazongas","Gerbils")) to ("Bad","Poor","Acceptable","Good","Great"))
:cl:
revert:Votes
/:cl:
=> Reverts: Voting
